name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão de execução ao Gradle
        run: chmod +x gradlew

      - name: Construir o APK Debug
        run: ./gradlew assembleDebug
        
      - name: Publicar Release Automática com o APK
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') == false
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          tag_name: v1.0-build
          name: "Versão mais recente do app"
          body: |
            APK gerado automaticamente pelo GitHub Actions a cada commit na branch principal a fim de visualizar o app durante o desenvolvimento.
            Último commit: ${{ github.sha }}  
          draft: false
          prerelease: false
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
